databases:
  - name: portfolio-db
    databaseName: portfolio_production
    user: portfolio
    plan: free

services:
  - type: web
    name: portfolio-web
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: e6c86acf1551be6650323a3ba7a7a433
        sync: false
      - key: RAILS_ENV
        value: production
